culinator 0.3;

recipe ck_cherry_limeade {
    title "Cherry Limeade";
    section "Better Than Store Bought";
    source "Crowded Kitchen";
    publisher "Crowded Kitchen";
    source_url "https://www.crowdedkitchen.com/cherry-limeade/";
    attribution "Recipe by Crowded Kitchen. See source URL for the original and updates.";
    total_time 20 min;
    description "Our cherry limeade is made with fresh sweet cherries and freshly squeezed lime juice for a perfectly balanced sweet-tart flavor. When the weather starts to heat up, this is the drink that I start to crave!";

    ingredient ingredient_1 measured by mass {
        name "2 cups fresh cherries (pitted and halved)";
    }

    ingredient ingredient_2 measured by mass {
        name "Zest and juice of 4 limes";
    }

    ingredient ingredient_3 measured by mass {
        name "3/4 cup granulated sugar";
    }

    ingredient ingredient_4 measured by mass {
        name "1 cup water";
    }

    ingredient ingredient_5 measured by mass {
        name "Sparkling water for topping";
    }

    process preparation {
        operation step_1 does prepare {
            note "To a small bowl, add the sugar and lime zest. Using your fingers, massage the sugar and zest together until fragrant and evenly incorporated.";
        }
        operation step_2 does prepare {
            note "To a small saucepan over medium low heat, add the cherries, sugar and zest mixture, and water. Cook over medium low heat and simmer for 10-15 minutes until the cherries have softened and begin to break down. You'll want to mash them a bit throughout the cooking process using a wooden spoon or similar utensil.";
            after step_1;
        }
        operation step_3 does prepare {
            note "Strain the cooked syrup to remove the solids, using a spatula or spoon to extract as much liquid as possible.";
            after step_2;
        }
        operation step_4 does prepare {
            note "Move the to refrigerator to cool. Once cooled, squeeze in the fresh juice from your zested limes.";
            after step_3;
        }
        operation step_5 does prepare {
            note "To make your soda, add about 1/4 to 1/3 cup (depending on how sweet you like your soda) of the syrup to an ice-filled glass, and top with sparkling water. Enjoy!";
            after step_4;
        }
    }
}
