culinator 0.3;

recipe ck_homemade_berry_granola {
    title "Homemade Berry Granola";
    section "Better Than Store Bought";
    source "Crowded Kitchen";
    publisher "Crowded Kitchen";
    source_url "https://www.crowdedkitchen.com/homemade-berry-granola/";
    attribution "Recipe by Crowded Kitchen. See source URL for the original and updates.";
    total_time 50 min;
    description "This homemade berry granola is naturally sweet, crunchy, and packed with dried berries, coconut flakes and maple syrup. It's perfect for an easy breakfast on top of yogurt, chia pudding, a smoothie bowl or as a quick snack (by the handful, of course)!";

    ingredient ingredient_1 measured by mass {
        name "3 cups old fashioned whole rolled oats";
    }

    ingredient ingredient_2 measured by mass {
        name "1 cup raw, unsalted sunflower seeds";
    }

    ingredient ingredient_3 measured by mass {
        name "1/3 cup melted coconut oil";
    }

    ingredient ingredient_4 measured by mass {
        name "½ cup maple syrup";
    }

    ingredient ingredient_5 measured by mass {
        name "1 teaspoon vanilla extract";
    }

    ingredient ingredient_6 measured by mass {
        name "1/2 teaspoon kosher salt";
    }

    ingredient ingredient_7 measured by mass {
        name "1 1/2 cups dried berries of choice (we used a mix of cranberries, cherries and blueberries)";
    }

    ingredient ingredient_8 measured by mass {
        name "1/3 cup shredded coconut (sweetened or unsweetened)";
    }

    process preparation {
        operation step_1 does prepare {
            note "Preheat oven to 300˚F / 150˚C. In a large bowl, stir together oats and sunflower seeds.";
        }
        operation step_2 does prepare {
            note "In a smaller bowl, whisk together coconut oil, maple syrup, vanilla, and salt.";
            after step_1;
        }
        operation step_3 does prepare {
            note "Pour the wet mixture over the dry and stir well to coat.";
            after step_2;
        }
        operation step_4 does prepare {
            note "Line a large, rimmed baking sheet with parchment paper and spread the granola mixture into an even layer. Bake for 15 minutes, then add coconut and stir. Return to oven for another 15-20 minutes (for a total baking time of 35 minutes), stirring once more halfway through the second baking period.";
            after step_3;
        }
        operation step_5 does prepare {
            note "Remove from the oven and immediately stir in dried fruit. Let it cool completely on the baking sheet before serving, and break into small pieces or clusters.";
            after step_4;
        }
    }
}
