culinator 0.3;

recipe ck_homemade_cinnamon_toast_crunch_cereal {
    title "Homemade Cinnamon Toast Crunch";
    section "Better Than Store Bought";
    source "Crowded Kitchen";
    publisher "Crowded Kitchen";
    source_url "https://www.crowdedkitchen.com/homemade-cinnamon-toast-crunch-cereal/";
    attribution "Recipe by Crowded Kitchen. See source URL for the original and updates.";
    total_time 72 min;
    description "You can make cinnamon toast crunch cereal at home, and it's way better than what you get in the box! This homemade cereal is crisp and crunchy (even when it's soaked in milk) and it has that trademark cinnamon sugar coating. Better yet, it's surprisingly easy to make, with fewer than 10 ingredients. This recipe is part of our Better Than Store-Bought series.";

    ingredient ingredient_1 measured by mass {
        name "1 1/4 cups all-purpose flour";
    }

    ingredient ingredient_2 measured by mass {
        name "¼ cup cornstarch";
    }

    ingredient ingredient_3 measured by mass {
        name "1/2 teaspoon baking powder";
    }

    ingredient ingredient_4 measured by mass {
        name "2 tablespoons granulated sugar";
    }

    ingredient ingredient_5 measured by mass {
        name "¼ teaspoon kosher salt";
    }

    ingredient ingredient_6 measured by mass {
        name "½ teaspoon ground cinnamon";
    }

    ingredient ingredient_7 measured by mass {
        name "8 tablespoons unsalted butter, chilled and cubed";
    }

    ingredient ingredient_8 measured by mass {
        name "5 tablespoons ice cold water";
    }

    ingredient ingredient_9 measured by mass {
        name "1/3 cup granulated sugar";
    }

    ingredient ingredient_10 measured by mass {
        name "2 teaspoons ground cinnamon";
    }

    ingredient ingredient_11 measured by mass {
        name "1 egg white + 2 teaspoons water";
    }

    process preparation {
        operation step_1 does prepare {
            note "To the bowl of a food processor, add the flour, cornstarch, baking powder, sugar, salt and cinnamon and pulse a few times to combine.";
        }
        operation step_2 does prepare {
            note "Add in the cubed butter and continue pulsing a few times until the butter forms pea-sized pieces. Add the water and pulse a few more times, just until incorporated. The dough should stick together when you press it together between two fingers.";
            after step_1;
        }
        operation step_3 does prepare {
            note "Turn the dough out onto a nonstick work surface, and use your hands to shape the dough into a rectangle, wrap in plastic wrap and refrigerate for 30 minutes. While the dough chills in the fridge, preheat your oven to 350˚F / 175˚C and line two sheet pans with parchment paper.";
            after step_2;
        }
        operation step_4 does prepare {
            note "In a bowl, stir together the sugar and cinnamon. In a separate bowl, whisk together the egg white and water.";
            after step_3;
        }
        operation step_5 does prepare {
            note "Remove the dough from the fridge and divide it in half. On a lightly floured surface, roll out half of the dough into a very thin (about 1/8\" thick) rectangle.";
            after step_4;
        }
        operation step_6 does prepare {
            note "Brush a very thin layer of egg white on the dough, then sprinkle with a thin layer of cinnamon sugar. Carefully lift the rectangle from the surface and transfer to a prepared baking sheet, placing it cinnamon sugar side down.";
            after step_5;
        }
        operation step_7 does prepare {
            note "Brush the top with a very thin layer of egg white, then sprinkle with an even layer of cinnamon sugar and press it into the dough gently.";
            after step_6;
        }
        operation step_8 does prepare {
            note "Using a small pastry cutter, first cut the dough lengthwise into 3/4\" thick strips. Then cut perpendicularly to the strips in 3/4\" increments. You should be left with a sheet pan full of roughly 3/4\" squares.";
            after step_7;
        }
        operation step_9 does prepare {
            note "Bake for 12 minutes, until the bottoms are golden brown. Let them cool completely on the sheet pan. Repeat with the other half of the dough.";
            after step_8;
        }
    }
}
