culinator 0.3;

recipe ck_homemade_peanut_butter_cookie_dough_protein_bars {
    title "Homemade Peanut Butter Cookie Dough Protein Bars";
    section "Better Than Store Bought";
    source "Crowded Kitchen";
    publisher "Crowded Kitchen";
    source_url "https://www.crowdedkitchen.com/homemade-peanut-butter-cookie-dough-protein-bars/";
    attribution "Recipe by Crowded Kitchen. See source URL for the original and updates.";
    total_time 10 min;
    description "It's so easy to make protein bars at home! Each of these Homemade Peanut Butter Cookie Dough Protein Bars has 15 grams of protein, and they taste just like chocolate chip cookie dough! They're no-bake, delicious, and are super easy to customize to your liking.";

    ingredient ingredient_1 measured by mass {
        name "1 cup* creamy peanut butter";
    }

    ingredient ingredient_2 measured by mass {
        name "6 tablespoons (3 oz) maple syrup";
    }

    ingredient ingredient_3 measured by mass {
        name "1 teaspoon vanilla extract";
    }

    ingredient ingredient_4 measured by mass {
        name "1/4 teaspoon salt";
    }

    ingredient ingredient_5 measured by mass {
        name "1 cup protein powder (~3 scoops)";
    }

    ingredient ingredient_6 measured by mass {
        name "1 cup oat flour**";
    }

    ingredient ingredient_7 measured by mass {
        name "1/2 cup mini chocolate chips";
    }

    process preparation {
        operation step_1 does prepare {
            note "Mix the peanut butter, maple syrup, vanilla extract, and salt with a strong spatula or a hand mixer.";
        }
        operation step_2 does prepare {
            note "Mix in the protein powder and oat flour. If the mixture is too dry and crumbly, add more peanut butter (1 tbsp at a time) until it comes together. (This can be very dependent on the brand/consistency of the peanut butter you use. You can also add a little more maple syrup to moisten the mixture.)";
            after step_1;
        }
        operation step_3 does prepare {
            note "Mix in the mini chocolate chips, scoop the mixture out into and 8x8\" or 9x9\" baking dish. Use the back of a measuring cup to smooth out the bars, then refrigerate for 1-2 hours, until firmed up.";
            after step_2;
        }
        operation step_4 does prepare {
            note "Cut into bars, and enjoy! Keep refrigerated in an airtight container.";
            after step_3;
        }
    }
}
