culinator 0.3;

recipe ck_homemade_orange_soda {
    title "Homemade Orange Soda";
    section "Better Than Store Bought";
    source "Crowded Kitchen";
    publisher "Crowded Kitchen";
    source_url "https://www.crowdedkitchen.com/homemade-orange-soda/";
    attribution "Recipe by Crowded Kitchen. See source URL for the original and updates.";
    total_time 20 min;
    description "If you love orange soda, you'll love this 3-ingredient homemade version even more! It's super refreshing, bubbly, delicious and easy to make. When it's this easy to make your own soda at home with fresh, seasonal ingredients, why even make a trip to the store?";

    ingredient ingredient_1 measured by mass {
        name "2 tablespoons orange zest (3-4 small oranges or 2 large oranges)";
    }

    ingredient ingredient_2 measured by mass {
        name "1 cup freshly squeezed orange juice (juice of 3-4 small oranges or 2 large oranges)";
    }

    ingredient ingredient_3 measured by mass {
        name "1/2 cup granulated sugar";
    }

    ingredient ingredient_4 measured by mass {
        name "Sparkling water";
    }

    process preparation {
        operation step_1 does prepare {
            note "Using a microplane, zest and 2 large or 3-4 smaller oranges, then juice them. Set the juice aside.";
        }
        operation step_2 does prepare {
            note "To a medium-sized bowl, add the granulated sugar and orange zest. Use your fingers to massage the sugar into the zest, until the sugar is uniformly orange in color.";
            after step_1;
        }
        operation step_3 does prepare {
            note "To a small saucepan over medium-low heat, add the zest and sugar mixture and the juice. Heat to a gentle simmer, stirring occasionally until all of the sugar has dissolved, then turn off the heat and let the zest steep in the syrup for at least 20 minutes, ideally until fully cooled.";
            after step_2;
        }
        operation step_4 does prepare {
            note "Once cooled, strain the syrup through a fine mesh sieve to remove the zest. Transfer the syrup to a mason jar or other storage container (we use this pump top bottle).";
            after step_3;
        }
        operation step_5 does prepare {
            note "To make your orange soda, add anywhere from 2-4 tablespoons of syrup to an ice-filled glass and then top off with sparkling water. Stir gently and enjoy!";
            after step_4;
        }
    }
}
