culinator 0.3;

recipe ck_pumpkin_spice_simple_syrup {
    title "Pumpkin Spice Simple Syrup";
    section "Better Than Store Bought";
    source "Crowded Kitchen";
    publisher "Crowded Kitchen";
    source_url "https://www.crowdedkitchen.com/pumpkin-spice-simple-syrup/";
    attribution "Recipe by Crowded Kitchen. See source URL for the original and updates.";
    total_time 25 min;
    description "With notes of cinnamon, cloves, and vanilla, this Pumpkin Spice Simple Syrup is the perfect way to add fall flavor to your favorite cocktails, your morning coffee, baked goods, or even a smoothie. This quick and easy recipe takes just 20 minutes, and keeps well in the fridge and freezer so you can enjoy all season long!";

    ingredient ingredient_1 measured by mass {
        name "1 cup maple syrup";
    }

    ingredient ingredient_2 measured by mass {
        name "1 cup water";
    }

    ingredient ingredient_3 measured by mass {
        name "1/2 cup pumpkin puree";
    }

    ingredient ingredient_4 measured by mass {
        name "4 whole cinnamon sticks";
    }

    ingredient ingredient_5 measured by mass {
        name "1 tablespoon finely minced fresh ginger";
    }

    ingredient ingredient_6 measured by mass {
        name "1 5 inch vanilla bean, (use the seeds and pod)";
    }

    ingredient ingredient_7 measured by mass {
        name "1 heaping teaspoon of whole cloves";
    }

    process preparation {
        operation step_1 does prepare {
            note "Add maple syrup, water, and pumpkin pureé to a small saucepan and whisk together over medium-high heat.";
        }
        operation step_2 does prepare {
            note "Using a small paring knife, carefully cut a slit in the vanilla bean from the top to the bottom. Using the edge of the knife, scrape the seeds from the vanilla bean pod. You may need to scrape more than once to make sure you get everything.";
            after step_1;
        }
        operation step_3 does prepare {
            note "Add cinnamon sticks, ginger, vanilla bean seeds (as well as the leftover pod) and cloves to the saucepan. Bring the mixture to a boil, then reduce heat slightly and simmer for 5-7 minutes.";
            after step_2;
        }
        operation step_4 does prepare {
            note "Remove from heat and let the mixture sit for 15-30 minutes. Remove the cinnamon sticks and vanilla bean pod with tongs, then strain the simple syrup through a fine mesh sieve. You'll have to use a spatula to push the liquid through, since the pumpkin puree residue makes it thick.";
            after step_3;
        }
        operation step_5 does prepare {
            note "Get as much liquid out as you possibly can, then transfer to a mason jar or other sealed container for storage.";
            after step_4;
        }
    }
}
