culinator 0.3;

recipe ck_slice_and_bake_christmas_cookies {
    title "Slice and Bake Christmas Cookies";
    section "Better Than Store Bought";
    source "Crowded Kitchen";
    publisher "Crowded Kitchen";
    source_url "https://www.crowdedkitchen.com/slice-and-bake-christmas-cookies/";
    attribution "Recipe by Crowded Kitchen. See source URL for the original and updates.";
    total_time 252 min;
    description "Remember those slice and bake cookies from your childhood that came in a tube? These homemade slice and bake Christmas cookies are surprisingly easy to make, taste better than the original, and are customizable to include your favorite holiday shapes. NOTE: The quantities below are for one shape, so multiply as desired depending on how many shapes you want to make.";

    ingredient ingredient_1 measured by mass {
        name "2 1/2 cups all purpose flour (spooned and leveled)";
    }

    ingredient ingredient_2 measured by mass {
        name "1 cup granulated sugar";
    }

    ingredient ingredient_3 measured by mass {
        name "3/4 cups unsalted butter, softened to room temperature";
    }

    ingredient ingredient_4 measured by mass {
        name "2 large eggs";
    }

    ingredient ingredient_5 measured by mass {
        name "1 teaspoon baking powder";
    }

    ingredient ingredient_6 measured by mass {
        name "1 teaspoon vanilla extract";
    }

    ingredient ingredient_7 measured by mass {
        name "1/2 teaspoon kosher salt";
    }

    ingredient ingredient_8 measured by mass {
        name "A few drops of food coloring (gel or natural)";
    }

    process preparation {
        operation step_1 does prepare {
            note "Add butter, sugar and vanilla extract to a large mixing bowl (or stand mixer). Beat at medium speed until light and fluffy, about 3 minutes.";
        }
        operation step_2 does prepare {
            note "Add in eggs one at a time, mixing just until combined.";
            after step_1;
        }
        operation step_3 does prepare {
            note "In a separate bowl, whisk together the flour, baking powder and salt.";
            after step_2;
        }
        operation step_4 does prepare {
            note "Add the dry ingredients to the wet ingredients in 3-4 batches, until the dough comes together. Add 1-2 tablespoons more flour if needed if the dough is too wet. If you used natural food coloring, you will likely need to add in the additional flour.";
            after step_3;
        }
        operation step_5 does prepare {
            note "Remove about about 10 ounces (~1/3) of the dough and place in a separate bowl. Add in several drops of food coloring and mix until combined.";
            after step_4;
        }
        operation step_6 does prepare {
            note "Place the colored dough in the freezer for 5-10 minutes, then roll out into a rectangle about 1/2-inch thick on a lightly floured surface. Return to the freezer for 30 minutes. This will make it much easier to cut out your chosen shape.";
            after step_5;
        }
        operation step_7 does prepare {
            note "Use a small cookie cutter (roughly 1.5\" across) to cut out your shape. Dip a finger in a little bit of water and rub on the floured side of the cookie before adhering to another cut out shape. This helps them stick together, but don’t overdo the water, you only need a tiny amount. Repeat with all cut out shapes until you have a log about 10 inches long.";
            after step_6;
        }
        operation step_8 does prepare {
            note "Return the log to the freezer for 2 hours, or until frozen solid. (We typically make these over two days and leave the log in the freezer overnight.) Remove from freezer and press the plain cookie dough directly onto and around the shape. Make sure to really press it in so you don’t end up with any gaps. We like to leave the ends open so we can see how much dough we need to make an even circle around the shape. Roll into a smooth log on a lightly floured surface.";
            after step_7;
        }
        operation step_9 does prepare {
            note "Wrap the log in plastic wrap and chill in the fridge for at least 30 minutes.";
            after step_8;
        }
        operation step_10 does prepare {
            note "Preheat your oven to 350˚F and line 2 baking sheets with parchment paper.";
            after step_9;
        }
        operation step_11 does prepare {
            note "When you’re ready to bake, slice the dough into 1/4” rounds, then space 2 inches apart on the baking sheets. Bake for ~12 minutes, or until the bottoms are light golden brown. Remove from the oven and let cool.";
            after step_10;
        }
    }
}
