use culinograph_models::NutritionFacts;

pub(crate) fn render(n: &NutritionFacts) -> String {
    let total_fat_dv = percent(n.total_fat_grams, 78.0);
    let sat_fat_dv = percent(n.saturated_fat_grams, 20.0);
    let cholesterol_dv = percent(n.cholesterol_milligrams, 300.0);
    let sodium_dv = percent(n.sodium_milligrams, 2300.0);
    let carbs_dv = percent(n.total_carbohydrate_grams, 275.0);
    let fiber_dv = percent(n.dietary_fiber_grams, 28.0);
    let added_dv = percent(n.added_sugars_grams, 50.0);
    format!(r#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 360 620" role="img" aria-label="Nutrition Facts"><style>text{{font-family:Arial,sans-serif;fill:#000}}.b{{font-weight:700}}.line{{stroke:#000}}.r{{text-anchor:end}}</style><rect width="360" height="620" fill="#fff" stroke="#000" stroke-width="3"/><text x="14" y="42" font-size="38" class="b">Nutrition Facts</text><line x1="14" y1="52" x2="346" y2="52" class="line" stroke-width="2"/><text x="14" y="76" font-size="14">{servings} servings per container</text><text x="14" y="99" font-size="15" class="b">Serving size</text><text x="346" y="99" font-size="15" class="b r">{serving}</text><line x1="14" y1="112" x2="346" y2="112" class="line" stroke-width="10"/><text x="14" y="137" font-size="13" class="b">Amount per serving</text><text x="14" y="177" font-size="28" class="b">Calories</text><text x="346" y="177" font-size="42" class="b r">{calories}</text><line x1="14" y1="190" x2="346" y2="190" class="line" stroke-width="6"/><text x="346" y="210" font-size="12" class="b r">% Daily Value*</text>{rows}<line x1="14" y1="510" x2="346" y2="510" class="line" stroke-width="8"/><text x="14" y="535" font-size="12">* Percent Daily Values are based on a 2,000 calorie diet.</text><text x="14" y="554" font-size="11">Generated by Culinograph. Verify values before regulated use.</text></svg>"#,
        servings=fmt(n.servings_per_container), serving=escape(&n.serving_size), calories=n.calories.round(),
        rows=rows(&[
            ("Total Fat", format!("{}g",fmt(n.total_fat_grams)),Some(total_fat_dv),true,0),
            ("Saturated Fat", format!("{}g",fmt(n.saturated_fat_grams)),Some(sat_fat_dv),false,14),
            ("Trans Fat", format!("{}g",fmt(n.trans_fat_grams)),None,false,14),
            ("Cholesterol", format!("{}mg",fmt(n.cholesterol_milligrams)),Some(cholesterol_dv),true,0),
            ("Sodium", format!("{}mg",fmt(n.sodium_milligrams)),Some(sodium_dv),true,0),
            ("Total Carbohydrate", format!("{}g",fmt(n.total_carbohydrate_grams)),Some(carbs_dv),true,0),
            ("Dietary Fiber", format!("{}g",fmt(n.dietary_fiber_grams)),Some(fiber_dv),false,14),
            ("Total Sugars", format!("{}g",fmt(n.total_sugars_grams)),None,false,14),
            ("Includes Added Sugars", format!("{}g",fmt(n.added_sugars_grams)),Some(added_dv),false,28),
            ("Protein", format!("{}g",fmt(n.protein_grams)),None,true,0),
        ]))
}
fn rows(rows: &[(&str,String,Option<i64>,bool,i32)]) -> String { rows.iter().enumerate().map(|(i,(name,value,dv,bold,indent))| { let y=232+i as i32*28; format!("<line x1=\"14\" y1=\"{}\" x2=\"346\" y2=\"{}\" class=\"line\"/><text x=\"{}\" y=\"{}\" font-size=\"14\"{}>{} {}</text>{}",y-19,y-19,14+indent,y,if *bold {" class=\"b\""}else{""},name,value,dv.map(|v|format!("<text x=\"346\" y=\"{}\" font-size=\"14\" class=\"b r\">{}%</text>",y,v)).unwrap_or_default()) }).collect() }
fn percent(v:f64,dv:f64)->i64{(v/dv*100.0).round() as i64} fn fmt(v:f64)->String{ if v.fract().abs()<0.01{format!("{v:.0}")}else{format!("{v:.1}")} } fn escape(v:&str)->String{v.replace('&',"&amp;").replace('<',"&lt;").replace('>',"&gt;")}
#[cfg(test)] mod test;
